export { default as Home } from './Home'
export { default as Login } from './Login'
export { default as NotFound } from './NotFound'
export { default as ProductDetail } from './ProductDetail'
export { default as Cart } from './Cart'
export { default as Address } from './Address'
export { default as Payment } from './Payment'